### ISSUE TITLE
lower required Python version?

### ISSUE THREAD

**Issue by FelixSchwarz** [sbordeyne/requests_har#2]
pyproject.toml mentions support for Python 3.7+ (via classifiers) but also has `python = "^3.10"` which translates into `Requires-Python: >=3.10,<4.0` in the distributed wheel.

Unfortunately, there are some environments where I can not use Python 3.10+. Would you accept PRs to lower the required version of Python, maybe even down to Python 3.6?

**Comment by sbordeyne** [comment]
The lowest version of python acceptable would be python3.8, since both 3.6 and 3.7 have reached EOL. 3.8 is due for EOL in a couple of months as well.

**Comment by FelixSchwarz** [comment]
> The lowest version of python acceptable would be python3.8, since both 3.6 and 3.7 have reached EOL. 3.8 is due for EOL in a couple of months as well.

Hmm, from my point of view that definition is too strict. For example some Linux distributions still support Python 2.7 (until mid 2024) and Python 3.6 (until 2028 or so) with security updates. Also there is pypy. Just looking at CPython's support cycles does not really fit the complexities of Python deployments. IMHO the `python_requires` should be of technical necessity (language syntax, stdlib API).

But of course I can accept a different view, just saying :-)

**Comment by sbordeyne** [comment]
I can be very strict about EOL support. Regardless of other python interpreter implementations, CPython is the default, base implementation, and sticking to old, unsupported versions for a few users is not in my plans.

Lastly, poetry, this package's dependancy manager requires python >= 3.8 to function, which is yet another reason to not drop the requirements lower.

Out of curiosity, which distros still support python 3.6 ? None of the very popular distros have their latest LTS still supporting that old a version

**Comment by FelixSchwarz** [comment]
> Out of curiosity, which distros still support python 3.6 ? None of the very popular distros have their latest LTS still supporting that old a version

That is correct if you just look for the "latest LTS". However I'm still seeing new versions being deployed to RHEL 7 and 8. Actually I am looking into requests_har to add some diagnostics capabilities to a Python application running on RHEL 7.

The poetry requirement is of course a good argument for requiring Python 3.8 (besides me having a strong dislike for poetry). I guess the only thing then is to remove the old versions from the classifiers.

I guess we'll just fork requests_har internally and deploy that version (without poetry). That approach just requires some shepherding - organizational laziness means fixes/improvements might be added just to the forked version which never makes it upstream then.

**Comment by sbordeyne** [comment]
python version has been lowered to 3.8, as discussed I'm not willing to go lower (made it a bit hellish to type properly as well).

I'm closing the issue, the package (1.1.0) has been published on pypi. Feel free to fork and remove typing if you need to
