### ISSUE TITLE
`HarDict.save()` should take a target file, not a directory

### ISSUE THREAD

**Issue by FelixSchwarz** [sbordeyne/requests_har#3]
https://github.com/sbordeyne/requests_har/blob/3b154320fba52887daf873580cb2f6dacd6e6411/requests_har/har.py#L203

I find it pretty unfortunate that `HarDict.save()` only takes a directory reference and it is not possible to set the exact target file. Using a specific file is helpful when I'm trying to automate things so could you consider also accepting a file reference?

If you really want to support passing in a directory, maybe do not create the directory. If the path exists and it is a directory, the current "magic". Otherwise just dump to the specified target?

I can work around easily by just ignoring the method but that feels like a wasted opportunity.

Also the calling save currently triggers an exception with a non-obvious error message if no request was recorded.

**Comment by sbordeyne** [comment]
If I recall correctly, this was done so that different sessions would be recorded and dumped in different files, all in the same directory, but with a timestamp in the filename.

I can easily modify the lib to support adding a file as the path argument, and add a bit of magic to keep the old behaviour (which is preferred) or dumping everything to a file.

I'll lookup the exception issue later this week

**Comment by FelixSchwarz** [comment]
Also one idea: If you auto-create a filename, you should return the file path. This is really helpful if you need to do something with the created file.

**Comment by sbordeyne** [comment]
A number of changes have been made : the save() method now takes in a file path as its argument. The file path is also returned from the method.

The whole library has been strictly typed, as well as tooling put in place (black, isort, mypy, pylint and pytest) to ensure code quality in the future.

New version has been published on pypi.org today which contains all of those fixes.

**Comment by FelixSchwarz** [comment]
Thank you :-)

**Comment by FelixSchwarz** [comment]
Just wanted to mention that I'm using requests har for a month now and with all the changes you made, it works pretty well for my use case.
